

DB_CONTAINER = postgres12-vf
DB_USERNAME = root
DB_PASSWORD = root
DB_DBNAME = vanillefraise
DB_PORT = 5432
DB_HOST = localhost


startdb:
	docker run $(DB_CONTAINER)

stopdb:
	docker stop $(DB_CONTAINER)

postgres:
	docker run --name $(DB_CONTAINER) -p $(DB_PORT):$(DB_PORT) -e POSTGRES_USER=$(DB_USERNAME) -e POSTGRES_PASSWORD=$(DB_PASSWORD) -d postgres:12-alpine 

createdb:
	docker exec -it $(DB_CONTAINER) createdb --username=$(DB_USERNAME) --owner=$(DB_USERNAME) $(DB_DBNAME)

dropdb:
	docker exec -it $(DB_CONTAINER) dropdb $(DB_DBNAME)

migrateup:
	migrate -path db/migration -database "postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_DBNAME)?sslmode=disable" -verbose up 1

migratedown:
	migrate -path db/migration -database "postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_DBNAME)?sslmode=disable" -verbose down 1
sqlc:
	sqlc generate

test:
	go test -v -cover ./...

server:
	go run .

run:
	CompileDaemon -command="make server"
