// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Recipe struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Image       string       `json:"image"`
	Active      sql.NullBool `json:"active"`
	Time        string       `json:"time"`
	Url         string       `json:"url"`
	Servings    int32        `json:"servings"`
	CreatedAt   time.Time    `json:"created_at"`
}

type RecipeCategory struct {
	ID     string       `json:"id"`
	Title  string       `json:"title"`
	Image  string       `json:"image"`
	Active sql.NullBool `json:"active"`
}

type RecipeCategoryRecipe struct {
	ID               string `json:"id"`
	RecipeID         string `json:"recipe_id"`
	RecipeCategoryID string `json:"recipe_category_id"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}

type UserInfo struct {
	ID     string    `json:"id"`
	Weight int32     `json:"weight"`
	Height int32     `json:"height"`
	Birth  time.Time `json:"birth"`
	UserID string    `json:"user_id"`
}
