// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Recipe struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Image       sql.NullString `json:"image"`
	Active      sql.NullBool   `json:"active"`
	Time        string         `json:"time"`
	Url         sql.NullString `json:"url"`
	Servings    sql.NullInt32  `json:"servings"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type RecipeCategory struct {
	ID     string         `json:"id"`
	Title  string         `json:"title"`
	Image  sql.NullString `json:"image"`
	Active sql.NullBool   `json:"active"`
}

type RecipeCategoryRecipe struct {
	ID               string         `json:"id"`
	RecipeID         sql.NullString `json:"recipe_id"`
	RecipeCategoryID sql.NullString `json:"recipe_category_id"`
}

type User struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type UserInfo struct {
	ID     string    `json:"id"`
	Weight int32     `json:"weight"`
	Height int32     `json:"height"`
	Birth  time.Time `json:"birth"`
	UserID string    `json:"user_id"`
}
