// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserInfo(ctx context.Context, arg CreateUserInfoParams) (UserInfo, error)
}

var _ Querier = (*Queries)(nil)
