// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: recipe_to_category.sql

package db

import (
	"context"
)

const assignRecipeToCategory = `-- name: AssignRecipeToCategory :one
INSERT INTO "RecipeCategory_Recipe" (
	id, recipe_id, recipe_category_id
) VALUES (
	$1, $2, $3
) RETURNING id, recipe_id, recipe_category_id
`

type AssignRecipeToCategoryParams struct {
	ID               string `json:"id"`
	RecipeID         string `json:"recipe_id"`
	RecipeCategoryID string `json:"recipe_category_id"`
}

func (q *Queries) AssignRecipeToCategory(ctx context.Context, arg AssignRecipeToCategoryParams) (RecipeCategoryRecipe, error) {
	row := q.db.QueryRowContext(ctx, assignRecipeToCategory, arg.ID, arg.RecipeID, arg.RecipeCategoryID)
	var i RecipeCategoryRecipe
	err := row.Scan(&i.ID, &i.RecipeID, &i.RecipeCategoryID)
	return i, err
}
