// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: recipe_category.sql

package db

import (
	"context"
)

const createRecipeCategory = `-- name: CreateRecipeCategory :one
INSERT INTO "RecipeCategory" (
	id, title, image
) VALUES (
	$1, $2, $3
) RETURNING id, title, image, active
`

type CreateRecipeCategoryParams struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Image string `json:"image"`
}

func (q *Queries) CreateRecipeCategory(ctx context.Context, arg CreateRecipeCategoryParams) (RecipeCategory, error) {
	row := q.db.QueryRowContext(ctx, createRecipeCategory, arg.ID, arg.Title, arg.Image)
	var i RecipeCategory
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Image,
		&i.Active,
	)
	return i, err
}
