// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: userinfo.sql

package db

import (
	"context"
	"time"
)

const createUserInfo = `-- name: CreateUserInfo :one
INSERT INTO "userInfo" (
	id, weight, height, birth, user_id
) VALUES (
	$1, $2, $3, $4, $5
) RETURNING id, weight, height, birth, user_id
`

type CreateUserInfoParams struct {
	ID     string    `json:"id"`
	Weight int32     `json:"weight"`
	Height int32     `json:"height"`
	Birth  time.Time `json:"birth"`
	UserID string    `json:"user_id"`
}

func (q *Queries) CreateUserInfo(ctx context.Context, arg CreateUserInfoParams) (UserInfo, error) {
	row := q.db.QueryRowContext(ctx, createUserInfo,
		arg.ID,
		arg.Weight,
		arg.Height,
		arg.Birth,
		arg.UserID,
	)
	var i UserInfo
	err := row.Scan(
		&i.ID,
		&i.Weight,
		&i.Height,
		&i.Birth,
		&i.UserID,
	)
	return i, err
}
